### ISSUE TITLE
请问是否不支持ssh(guacd)和rdp录屏?

### ISSUE THREAD

**Issue by zhu0629** [dushixiang/next-terminal#206]
docker-compose部署的, sqlite数据库
测试发现guacd连接ssh无法录屏, 历史会话里面查看回放按钮是灰色
rdp也无法录屏

用原生ssh连接可以录屏

**Comment by dushixiang** [comment]
> docker-compose部署的, sqlite数据库
> 
> 测试发现guacd连接ssh无法录屏, 历史会话里面查看回放按钮是灰色
> 
> rdp也无法录屏
> 
> 
> 
> 用原生ssh连接可以录屏
> 
> 

支持的，请问是什么操作系统部署的？

**Comment by zhu0629** [comment]
使用教程内的docker-compose部署的，
sqlite和外部mysql都试过，
几乎没改动教程内的yml文件

版本是1.2.2

尝试在windows docker和群晖上都无法查看回放。（仅用原生连接ssh可以回放）

**Comment by zhu0629** [comment]
```
version: '3.3'
services:
  guacd:
    container_name: guacd
    image: dushixiang/guacd:1.3.0
    restart: always
    volumes:
      - ./data:/usr/local/next-terminal/data

  next-terminal:
    container_name: next-terminal
    image: dushixiang/next-terminal:latest
    restart: always
    environment:
      DB: sqlite
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
      SSHD_ENABLE: "true"
    ports:
      - 8088:8088
      - 8089:8089
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data:/usr/local/next-terminal/data

```

**Comment by dushixiang** [comment]
> ```
> version: '3.3'
> services:
>   guacd:
>     container_name: guacd
>     image: dushixiang/guacd:1.3.0
>     restart: always
>     volumes:
>       - ./data:/usr/local/next-terminal/data
> 
>   next-terminal:
>     container_name: next-terminal
>     image: dushixiang/next-terminal:latest
>     restart: always
>     environment:
>       DB: sqlite
>       GUACD_HOSTNAME: guacd
>       GUACD_PORT: 4822
>       SSHD_ENABLE: "true"
>     ports:
>       - 8088:8088
>       - 8089:8089
>     volumes:
>       - /etc/localtime:/etc/localtime
>       - ./data:/usr/local/next-terminal/data
> ```

已经定位到问题了，稍等一下就会推送镜像。

**Comment by dushixiang** [comment]
已推送镜像。

**Comment by zhu0629** [comment]
@dushixiang 问题并未得到解决, 使用最新的镜像测试问题依旧

**Comment by zhu0629** [comment]
```
guacd[8]: INFO: Guacamole proxy daemon (guacd) version 1.3.0 started

guacd[8]: INFO: Listening on host 0.0.0.0, port 4822

guacd[8]: INFO: Creating new client for protocol "rdp"

guacd[8]: INFO: Connection ID is "$a3de2b71-e021-459f-aee5-4d86c8ce203c"

guacd[10]: INFO: Security mode: Negotiate (ANY)

guacd[10]: INFO: Resize method: reconnect

guacd[10]: INFO: User "@cabbd998-8763-43e9-bcfc-4fde735b333e" joined connection "$a3de2b71-e021-459f-aee5-4d86c8ce203c" (1 users now present)

guacd[10]: ERROR: Creation of recording failed: Permission denied

guacd[10]: INFO: Loading keymap "base"

guacd[10]: INFO: Loading keymap "en-us-qwerty"

guacd[10]: INFO: Connected to RDPDR 1.12 as client 0x0002

guacd[10]: INFO: Connected to RDPDR 1.12 as client 0x0001

guacd[10]: INFO: RDPDR user logged on

guacd[10]: INFO: User "@cabbd998-8763-43e9-bcfc-4fde735b333e" disconnected (0 users remain)

guacd[10]: INFO: Last user of connection "$a3de2b71-e021-459f-aee5-4d86c8ce203c" disconnected

guacd[10]: INFO: Internal RDP client disconnected

guacd[8]: INFO: Connection "$a3de2b71-e021-459f-aee5-4d86c8ce203c" removed.
```



```

当前数据库模式为：sqlite

Session Manager   Run

⇨ http server started on [::]:8088

Session Manager 85cc7441-fac4-4f43-b806-a23386e6911e  Run

Session Manager 85cc7441-fac4-4f43-b806-a23386e6911e End
```

**Comment by zhu0629** [comment]
看了日志才知道, 挂载的data目录没权限, 在宿主机上`chmod 777 data`即可

**Comment by towserchen** [comment]
这个补充很重要，配置后无法录像是宿主目录权限问题，需要 `chmod 777 -R data`

**Comment by dushixiang** [comment]
修改了 guacd 容器的默认用户为 root

**Comment by sunmd01** [comment]
按照官网流程，使用 docker-compose 部署，guacd 和 rdp 录屏依然是灰色

```yml
version: "3.3"
services:
    guacd:
        image: dushixiang/guacd:latest
        user: root
        volumes:
            - /root/next-terminal/data:/usr/local/next-terminal/data
        restart:
            always
    next-terminal:
        image: dushixiang/next-terminal:latest
        user: root
        environment:
            DB: sqlite
            GUACD_HOSTNAME: guacd
            GUACD_PORT: 4822
        ports:
            - "8088:8088"
        volumes:
            - /etc/localtime:/etc/localtime
            - /root/next-terminal/data:/usr/local/next-terminal/data'
        restart:
            always

```
