### ISSUE TITLE
「资产」无法通过「资产标签」过滤

### ISSUE THREAD

**Issue by killbus** [dushixiang/next-terminal#33]
「资产列表」页面，尝试通过「资产标签」过滤，返回结果总是空。

确认是：使用默认 `sqlite` 时才会出现，`mysql` 正常。

**docker-compose.yml**

```yaml
version: '3.3'

services:
  mariadb:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_DATABASE=next_terminal
      - MYSQL_USER=next_terminal
      - MYSQL_PASSWORD=next_terminal
  next-terminal:
    image: ghcr.io/dushixiang/next-terminal:latest
    ports:
      - 8088:8088
    environment:
      - DB=mysql
      - MYSQL_HOSTNAME=mariadb
      - MYSQL_USERNAME=next_terminal
      - MYSQL_PASSWORD=next_terminal
      - MYSQL_DATABASE=next_terminal
```
