### ISSUE TITLE
ipv6环境docker部署，无法ssh接入ipv6资产，求救！

### ISSUE THREAD

**Issue by cheat0916** [dushixiang/next-terminal#433]
我用的VC的kvm的ipv6小鸡，在docker中部署的next-terminal，都是按着官方文档来的，也开启了sshd。
想添加vps作为webssh使用，可是添加资产后无法连接，谷歌和ai帮不到我，求！
![](https://xiray.cf/file/019328dc59fa08e3cea40.png)
![](https://xiray.cf/file/cac955057feff3b46f6d8.png)
 

后来我安装了warp，next-terminal内添加v4资产就可以正常ssh接入了。但是v6依旧不行，同样的错误提示。
我又试着在v6地址前后添加“[]”，结果错误提示变成了：
“创建SSH客户端失败：dial tcp [****：****：****：****：****：****：****：****]:22: connect: cannot assign requested address”

下面是我部署next-terminal时的docker-compose.yml：

```
version: '3.3'
services:
  guacd:
    image: dushixiang/guacd:latest
    volumes:
      - ./data:/usr/local/next-terminal/data
    restart: always
    network_mode: host

  next-terminal:
    image: dushixiang/next-terminal:latest
    environment:
      DB: sqlite
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
      SSHD_ENABLE: "true"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data:/usr/local/next-terminal/data
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
    restart: always
    network_mode: host
```
