### ISSUE TITLE
配置文件不生效

### ISSUE THREAD

**Issue by syanpun** [dushixiang/next-terminal#453]
k8s部署，把config.yml挂载到`/usr/local/next-terminal/config.yml`或者`/etc/next-terminal/config.yml`均不生效，如下面截图，配置文件指定使用mysql，启动日志输出使用sqlite

<img width="589" alt="image" src="https://github.com/dushixiang/next-terminal/assets/57906917/d48fefae-760b-4223-a0fd-edbd27172f29">

<img width="499" alt="image" src="https://github.com/dushixiang/next-terminal/assets/57906917/d6a8ba72-ed50-4580-87d2-2aff67620c21">

config.yml:
```yaml
debug: false
demo: false
db: mysql
mysql:
  hostname: mysql
  port: 3306
  username: xxx
  password: xxx
  database: next-terminal
guacd:
  hostname: guacd
  port: 4822
  recording: /usr/local/next-terminal/data/recording
  driver: /usr/local/next-terminal/data/driver
sshd:
  enable: true
  addr: 0.0.0.0:8089
  key: /usr/local/next-terminal/ssh/id_rsa
```

只能通过环境变量的方式指定mysql相关配置
