### ISSUE TITLE
docker部署無法正常開啟以及1.X設定檔匯出有問題

### ISSUE THREAD

**Issue by taiwan-king** [dushixiang/next-terminal#472]
[config.yaml](panic: read config err: open /etc/next-terminal/config.yaml: no such file or directory)

之前1.X版本並不需要自行創建此檔案，回頭去看之前版本此檔案發現內容也是空的
2.X就會出問題，就算是全新安裝一樣

大老可以提供docker-compose.yml文檔嗎?

**Comment by yanhao98** [comment]
https://docs.next-terminal.typesafe.cn/install/pro-install.html#配置文件详解

- docker-compose.yaml
```yaml
      - type: bind
        source: ./config.yaml
        target: /etc/next-terminal/config.yaml
```
